{% set name = "yacs" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e47a59c9852b5d9cdc3777587864e9771060340d8f1b92b2c68f45244550c02

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - pyyaml
  run:
    - python
    - pyyaml

test:
  imports:
    - yacs

about:
  home: https://github.com/rbgirshick/yacs
  license: Apache 2.0
  license_family: Apache
  summary: YACS -- Yet Another Configuration System
  description: YACS -- Yet Another Configuration System
  doc_url: https://github.com/rbgirshick/yacs
  dev_url: https://github.com/rbgirshick/yacs

extra:
  recipe-maintainers:
    - hadim
